export const PROJECT_ROOT = '/progetti'
export const PROJECT_IN_CORSO = PROJECT_ROOT + '/in-corso'
export const PROJECT_COMPLETATI = PROJECT_ROOT + '/completati'
export const PROJECT_BOZZA = PROJECT_ROOT + '/in-bozza'
export const PROJECT_ROOT_NEW = PROJECT_ROOT + '/edita'
export const FEATURE_PATH = PROJECT_ROOT + '/edita/caratteristiche'
export const STEP_FORM_PATH = PROJECT_ROOT + '/edita/step/'
export const STEP_FORM_PATH_NEW = PROJECT_ROOT + '/edita/step/new'
export const PROJECT_EDIT = PROJECT_ROOT + '/modifica'

