export const ROOT_API = 'http://localhost:3000/api'
export const PROJECT_API = `projects/`
export const GET_PROJECTS_API = PROJECT_API + 'all'
export const UPDATE_PROJECT_API = PROJECT_API + 'update'
export const UPDATE_STEP_API = PROJECT_API + 'update/step'
export const GET_PROJECT_BY_PATH_API = PROJECT_API + 'path/'
export const GET_PROJECT_API = PROJECT_API + 'find'
export const UPLOAD_IMAGE_API = PROJECT_API + 'uploadImage/'
export const IMAGE_API = PROJECT_API + 'image/'
export const GET_STEPS_BY_ID_API = PROJECT_API + `steps/`
export const MY_PROJECT_API = `myProjects/`
export const UPDATE_LAST_STEP_API = MY_PROJECT_API + 'updateLastStep'
